source 'https://rubygems.org'

gem 'json', '2.7.2'
gem 'yajl-ruby', '1.4.3'

gem 'unicorn', '6.1.0'
gem 'sinatra', '4.0.0'
gem 'pg', '1.5.6'
gem 'maxmind-geoip2', '1.1.0'

gem 'rack-unreloader'
gem 'rexml', '3.3.1'

gem 'sinatra-cors', '~> 1.2'
